name: k6 graphQl Test

on:
  push:
    branches:
      - main    # Run at 1 PM every day

jobs:
  k6_local_test:
    name: GraphQL Load Test
    runs-on: ubuntu-latest
    container: docker://golang:1.19-alpine
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1
    
      - name: Install xk6
        run: go install go.k6.io/xk6/cmd/xk6@latest
    
      - name: Build xk6-counter binary
        run: xk6 build --with github.com/grafana/xk6-dashboard@latest
    
      - name: Run k6 extension test
        run: |
          # Check if graphql-test.html exists
          if[ ! -f graphql-test.html];then
            echo "Creating graphql-test.html"
            echo "this is a test content">graphql-test.html
          fi
          ./k6 run --out dashboard=report=greaphql-test.html graphql.js

      - name: Upload Performance Test results
        uses: actions/upload-artifact@v3
        with:
          name: graphQL Test report
          path: graphql-test.html
      
