
name: k6 Browser Dashboard Test

on:
    push:
      branches:
        - main

jobs:
  k6_local_test:
    name: xk6 dashboard Broswer Test 
    runs-on: ubuntu-latest
    container: docker://golang:1.19-alpine

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install xk6
        run: go install go.k6.io/xk6/cmd/xk6@latest

      - name: Build k6-browser script
        run: xk6 build --output xk6-browser --with github.com/grafana/xk6-browser
             
      
      - name: Build xk6-dashboard
        run: xk6 build --with github.com/grafana/xk6-dashboard@latest


      - name: Run k6 extension test
        run: |
          # Check if browser-report.html exists
          if [ ! -f browser-report.html ]; then
            echo "Creating browser-report.html"
            echo "this is a test content" > browser-report.html
          fi
          export K6_BROWSER_ENABLED=true
           ./k6 run --out dashboard=report=browser-report.html browserTest.js
        env: 
          K6_BROWSER_ENABLED: TRUE

      - name: Archive Performance Test results
        run: |

          # Cleanup old test reports, keep only the last 5
          ls -t test-report-* | tail -n +6 | xargs rm -f


      - name: Upload Performance Test results
        uses: actions/upload-artifact@v3
        with:
          name: k6-Dashboard-browser
          path: browser-report.html
      

    
